version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # Mount custom configuration
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teams_time_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  team-time:
    image: team-time:latest
    build:
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: "no" # Again, a different restart policy might be more suitable
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB_NAME: teams_time_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root

volumes:
  mysql_data: